services:
  Feroz\DynamicDbBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Resources,Tests}'
    autowire: true

  Feroz\DynamicDbBundle\Registry\DynamicRegistryDecorator:
    decorates: doctrine
    autowire: true
    arguments:
      $decorated: '@.inner'